name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

# Cancel any in-progress job or previous runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  actions: read
  contents: read

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Setup pnpm first
      - uses: pnpm/action-setup@v2
        with:
          version: 10

      # Setup Node.js with pnpm cache
      - uses: actions/setup-node@v4
        with:
          node-version: 22.16.0
          cache: "pnpm"

      - name: Install dependencies
        timeout-minutes: 5
        env:
          CI: true
          # Cypress optimizations
          CYPRESS_INSTALL_BINARY: 0
          CYPRESS_RUN_BINARY: 0
          CYPRESS_SKIP_BINARY_INSTALL: true
          CYPRESS_CACHE_FOLDER: ~/.cache/Cypress
        run: pnpm install --frozen-lockfile --strict-peer-dependencies

      - uses: nrwl/nx-set-shas@v4



      # Build the applications
      - run: npx nx run-many --target=build --all

      - name: Ensure dist folder exists
        run: mkdir -p dist

      - name: Copy index.html to dist
        run: cp index.html dist/

      - name: Copy staticwebapp.config.json to dist
        run: cp staticwebapp.config.json dist/

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AMBITIOUS_PLANT_067CBD51E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          app_location: "/dist"
          skip_app_build: true
          skip_api_build: true
