name: CI (No Cloud)

on:
  # pull_request:
  #   branches:
  #     - main
  workflow_dispatch: # Manual trigger only

# # Cancel any in-progress job or previous runs
# concurrency:
#   group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
#   cancel-in-progress: true

permissions:
  actions: read
  contents: read

jobs:
  main:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      # This command does exist ignore the linting errors
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # This command does exist ignore the linting errors
      - uses: actions/setup-node@v4
        with:
          node-version: 22.17.0
          cache: "npm"

      - run: npm ci
      # This command does exist ignore the linting errors
      - uses: nrwl/nx-set-shas@v4

      # Run tests
      - run: npm test -- --skip-nx-cache
