name: Deploy

on:
  push:
    branches:
      - main

# Cancel any in-progress job or previous runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: read
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 22.16.0
          cache: 'npm'

      - run: npm ci

      - uses: nrwl/nx-set-shas@v4

      # Build the applications
      - run: npx nx run-many --target=build --all

      # Deploy to Azure Web App using FTPS
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: madelk
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
